import Head from 'next/head';

interface IProps {
	children: JSX.Element;
}

export default function MainLayout({ children }: IProps) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<>
				<nav>Navegacion</nav>
				<aside>sidebar</aside>
				<aside>publicidad</aside>
				<main>{children}</main>
				<footer>footer</footer>
			</>
		</>
	);
}
