GET https://flexzin-ecommerce.vercel.app/api/auth/change-password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzkxODI1MzMsImVtYWlsIjoiam9zZWxhdGluZXMzM0BnbWFpbC5jb20iLCJpYXQiOjE2NzkwOTYxMzN9.AdtJknUKTOu4chlMzagBJsqRHflhCi1Q4zulBzisL6I

###

PUT https://flexzin-ecommerce.vercel.app/api/auth/change-password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzkxODI1MzMsImVtYWlsIjoiam9zZWxhdGluZXMzM0BnbWFpbC5jb20iLCJpYXQiOjE2NzkwOTYxMzN9.AdtJknUKTOu4chlMzagBJsqRHflhCi1Q4zulBzisL6I
content-type: application/json

{
	"email": "joselatines@gmail.com",
	"password": "mainroott"
}
