GET https://flexzin-ecommerce.vercel.app/api/auth/login

###

POST https://flexzin-ecommerce.vercel.app/api/auth/login
content-type: application/json

{
 "email": "joselatines@gmail.com",
 "password": "mainroott"
}