GET http://localhost:3000/api/products

###
DELETE  http://localhost:3000/api/products/642232172d37a1557df1443f

###

POST https://flexzin-ecommerce.vercel.app/api/products
content-type: application/json

{
	"title": "Camisa Flexzin",
	"price": 33,
	"salePrice": 15,
	"rating": 10,
	"qty": 1,
	"currency": "USD",
	"description": "Exclusivo",
	"reviewsCount": 23,
	"images":["https://i.postimg.cc/g2qz9xtF/270155440-607693960536710-330534241042917093-n.jpg0"]
}
