GET http://localhost:3000/api/products

###
DELETE  http://localhost:3000/api/products/642232172d37a1557df1443f

###

POST https://flexzin-ecommerce.vercel.app/api/products
content-type: application/json

{
	"title": "Camisa Bad Bunny",
	"price": 43,
	"salePrice": 23,
	"rating": 6,
	"qty": 1,
	"currency": "USD",
	"description": "Especial",
	"reviewsCount": 10,
	"images":["https://i.postimg.cc/prqky7DB/280300147-358138799715324-3230341352896785735-n.jpg"]
}
