GET https://flexzin-ecommerce.vercel.app/api/users

###

POST https://flexzin-ecommerce.vercel.app/api/users
content-type: application/json

{
	"email": "probandito@gmail.com",
	"username": "test user",
	"password": "123adfadsf45"
}
